"""Add clicked model

Revision ID: 5eca67d8db28
Revises: f894d11f2b91
Create Date: 2024-09-18 13:45:13.509641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eca67d8db28'
down_revision = 'f894d11f2b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicked', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicked', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
